trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'smartbuildingweather'

stages:

# =========================
# BUILD STAGE
# =========================

- stage: Build
  displayName: Build Stage

  jobs:
  - job: BuildJob
    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: Install Dependencies

    - script: |
        python -m py_compile app.py
      displayName: Validate Python Code

    - task: Docker@2
      inputs:
        containerRegistry: 'AzureContainerRegistry'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest

# =========================
# DEPLOY STAGE
# =========================

- stage: Deploy
  displayName: Deploy Stage

  dependsOn: Build

  jobs:
  - deployment: DeployWebApp

    environment: 'production'

    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Azure-Service-Connection'
              appName: 'smart-building-weather-app'
              containers: |
                smartbuildingweather.azurecr.io/smartbuildingweather:latest
